# Deploy to GitHub pages when a branch is merged with develop
name: Deploy to GitHub Pages

# When there is a push or pull_request on develop
on:
  push:
    branches: [develop]

# Create a job
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

        with:
          ref: develop

      - name: install dependencies
        run: yarn install
      - name: Deploy to GH-Pages
        run: |
          git config user.name ${{secrets.USERNAME}} 
          git config user.email ${{secrets.EMAIL}}
          git remote set-url origin https://${{secrets.TOKEN}}@github.com/${{secrets.USERNAME}}/userresearch.git

          git config --global user.name "HarryAmmon" && git config --global user.email "harry_a99@hotmail.co.uk"

          yarn deploy
