# Deploy to GitHub pages when a branch is merged with develop
name: Deploy to GitHub Pages

# When there is a push or pull_request on develop
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

# Create a job
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    steps:
      - uses: actions/checkout@v2
      - run: echo hello world
